CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  body TEXT NOT NULL,
  img VARCHAR NOT NULL,
  kind VARCHAR NOT NULL,
  duration INTEGER NOT NULL,
  user_id INTEGER REFERENCES users NOT NULL
)
